//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldlineLiveServiceReference
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class Student : object
    {
        
        private int RollNoField;
        
        private string NameField;
        
        private System.DateTime DateOfBirthField;
        
        private double PercentageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RollNo
        {
            get
            {
                return this.RollNoField;
            }
            set
            {
                this.RollNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Percentage
        {
            get
            {
                return this.PercentageField;
            }
            set
            {
                this.PercentageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bank", Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class Bank : object
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankDetails", Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class BankDetails : object
    {
        
        private string BankField;
        
        private string IfscField;
        
        private string MicrCodeField;
        
        private string BranchField;
        
        private string StdCodeField;
        
        private string ContactField;
        
        private string CityField;
        
        private string DistrictField;
        
        private string StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Bank
        {
            get
            {
                return this.BankField;
            }
            set
            {
                this.BankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Ifsc
        {
            get
            {
                return this.IfscField;
            }
            set
            {
                this.IfscField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MicrCode
        {
            get
            {
                return this.MicrCodeField;
            }
            set
            {
                this.MicrCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Branch
        {
            get
            {
                return this.BranchField;
            }
            set
            {
                this.BranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StdCode
        {
            get
            {
                return this.StdCodeField;
            }
            set
            {
                this.StdCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Contact
        {
            get
            {
                return this.ContactField;
            }
            set
            {
                this.ContactField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string District
        {
            get
            {
                return this.DistrictField;
            }
            set
            {
                this.DistrictField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }

        internal List<BankDetails> toList()
        {
            throw new NotImplementedException();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training", ConfigurationName="WorldlineLiveServiceReference.SoapDemoSoap")]
    public interface SoapDemoSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://arctechinfo.com/webservies/worldline-training/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldlineLiveServiceReference.HelloWorldResponse> HelloWorldAsync(WorldlineLiveServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://arctechinfo.com/webservies/worldline-training/GetOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldlineLiveServiceReference.GetOrdersResponse> GetOrdersAsync(WorldlineLiveServiceReference.GetOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://arctechinfo.com/webservies/worldline-training/GetBankList", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldlineLiveServiceReference.GetBankListResponse> GetBankListAsync(WorldlineLiveServiceReference.GetBankListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://arctechinfo.com/webservies/worldline-training/GetBranchDetailsByIfsc", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldlineLiveServiceReference.GetBranchDetailsByIfscResponse> GetBranchDetailsByIfscAsync(WorldlineLiveServiceReference.GetBranchDetailsByIfscRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://arctechinfo.com/webservies/worldline-training/GetBranchDetailsByBank", ReplyAction="*")]
        System.Threading.Tasks.Task<WorldlineLiveServiceReference.GetBranchDetailsByBankResponse> GetBranchDetailsByBankAsync(WorldlineLiveServiceReference.GetBranchDetailsByBankRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public WorldlineLiveServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(WorldlineLiveServiceReference.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public WorldlineLiveServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(WorldlineLiveServiceReference.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrders", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public WorldlineLiveServiceReference.GetOrdersRequestBody Body;
        
        public GetOrdersRequest()
        {
        }
        
        public GetOrdersRequest(WorldlineLiveServiceReference.GetOrdersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetOrdersRequestBody
    {
        
        public GetOrdersRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersResponse", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public WorldlineLiveServiceReference.GetOrdersResponseBody Body;
        
        public GetOrdersResponse()
        {
        }
        
        public GetOrdersResponse(WorldlineLiveServiceReference.GetOrdersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class GetOrdersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldlineLiveServiceReference.Student[] GetOrdersResult;
        
        public GetOrdersResponseBody()
        {
        }
        
        public GetOrdersResponseBody(WorldlineLiveServiceReference.Student[] GetOrdersResult)
        {
            this.GetOrdersResult = GetOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBankListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBankList", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public WorldlineLiveServiceReference.GetBankListRequestBody Body;
        
        public GetBankListRequest()
        {
        }
        
        public GetBankListRequest(WorldlineLiveServiceReference.GetBankListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBankListRequestBody
    {
        
        public GetBankListRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBankListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBankListResponse", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public WorldlineLiveServiceReference.GetBankListResponseBody Body;
        
        public GetBankListResponse()
        {
        }
        
        public GetBankListResponse(WorldlineLiveServiceReference.GetBankListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class GetBankListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldlineLiveServiceReference.Bank[] GetBankListResult;
        
        public GetBankListResponseBody()
        {
        }
        
        public GetBankListResponseBody(WorldlineLiveServiceReference.Bank[] GetBankListResult)
        {
            this.GetBankListResult = GetBankListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBranchDetailsByIfscRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBranchDetailsByIfsc", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public WorldlineLiveServiceReference.GetBranchDetailsByIfscRequestBody Body;
        
        public GetBranchDetailsByIfscRequest()
        {
        }
        
        public GetBranchDetailsByIfscRequest(WorldlineLiveServiceReference.GetBranchDetailsByIfscRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class GetBranchDetailsByIfscRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IfscCode;
        
        public GetBranchDetailsByIfscRequestBody()
        {
        }
        
        public GetBranchDetailsByIfscRequestBody(string IfscCode)
        {
            this.IfscCode = IfscCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBranchDetailsByIfscResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBranchDetailsByIfscResponse", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public WorldlineLiveServiceReference.GetBranchDetailsByIfscResponseBody Body;
        
        public GetBranchDetailsByIfscResponse()
        {
        }
        
        public GetBranchDetailsByIfscResponse(WorldlineLiveServiceReference.GetBranchDetailsByIfscResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class GetBranchDetailsByIfscResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldlineLiveServiceReference.BankDetails GetBranchDetailsByIfscResult;
        
        public GetBranchDetailsByIfscResponseBody()
        {
        }
        
        public GetBranchDetailsByIfscResponseBody(WorldlineLiveServiceReference.BankDetails GetBranchDetailsByIfscResult)
        {
            this.GetBranchDetailsByIfscResult = GetBranchDetailsByIfscResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBranchDetailsByBankRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBranchDetailsByBank", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public WorldlineLiveServiceReference.GetBranchDetailsByBankRequestBody Body;
        
        public GetBranchDetailsByBankRequest()
        {
        }
        
        public GetBranchDetailsByBankRequest(WorldlineLiveServiceReference.GetBranchDetailsByBankRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class GetBranchDetailsByBankRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bankName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int offset;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int rowCount;
        
        public GetBranchDetailsByBankRequestBody()
        {
        }
        
        public GetBranchDetailsByBankRequestBody(string bankName, int offset, int rowCount)
        {
            this.bankName = bankName;
            this.offset = offset;
            this.rowCount = rowCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBranchDetailsByBankResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBranchDetailsByBankResponse", Namespace="http://arctechinfo.com/webservies/worldline-training", Order=0)]
        public WorldlineLiveServiceReference.GetBranchDetailsByBankResponseBody Body;
        
        public GetBranchDetailsByBankResponse()
        {
        }
        
        public GetBranchDetailsByBankResponse(WorldlineLiveServiceReference.GetBranchDetailsByBankResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://arctechinfo.com/webservies/worldline-training")]
    public partial class GetBranchDetailsByBankResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WorldlineLiveServiceReference.BankDetails[] GetBranchDetailsByBankResult;
        
        public GetBranchDetailsByBankResponseBody()
        {
        }
        
        public GetBranchDetailsByBankResponseBody(WorldlineLiveServiceReference.BankDetails[] GetBranchDetailsByBankResult)
        {
            this.GetBranchDetailsByBankResult = GetBranchDetailsByBankResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SoapDemoSoapChannel : WorldlineLiveServiceReference.SoapDemoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SoapDemoSoapClient : System.ServiceModel.ClientBase<WorldlineLiveServiceReference.SoapDemoSoap>, WorldlineLiveServiceReference.SoapDemoSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SoapDemoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SoapDemoSoapClient.GetBindingForEndpoint(endpointConfiguration), SoapDemoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapDemoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SoapDemoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapDemoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SoapDemoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapDemoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldlineLiveServiceReference.HelloWorldResponse> WorldlineLiveServiceReference.SoapDemoSoap.HelloWorldAsync(WorldlineLiveServiceReference.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldlineLiveServiceReference.HelloWorldResponse> HelloWorldAsync()
        {
            WorldlineLiveServiceReference.HelloWorldRequest inValue = new WorldlineLiveServiceReference.HelloWorldRequest();
            inValue.Body = new WorldlineLiveServiceReference.HelloWorldRequestBody();
            return ((WorldlineLiveServiceReference.SoapDemoSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldlineLiveServiceReference.GetOrdersResponse> WorldlineLiveServiceReference.SoapDemoSoap.GetOrdersAsync(WorldlineLiveServiceReference.GetOrdersRequest request)
        {
            return base.Channel.GetOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldlineLiveServiceReference.GetOrdersResponse> GetOrdersAsync()
        {
            WorldlineLiveServiceReference.GetOrdersRequest inValue = new WorldlineLiveServiceReference.GetOrdersRequest();
            inValue.Body = new WorldlineLiveServiceReference.GetOrdersRequestBody();
            return ((WorldlineLiveServiceReference.SoapDemoSoap)(this)).GetOrdersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldlineLiveServiceReference.GetBankListResponse> WorldlineLiveServiceReference.SoapDemoSoap.GetBankListAsync(WorldlineLiveServiceReference.GetBankListRequest request)
        {
            return base.Channel.GetBankListAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldlineLiveServiceReference.GetBankListResponse> GetBankListAsync()
        {
            WorldlineLiveServiceReference.GetBankListRequest inValue = new WorldlineLiveServiceReference.GetBankListRequest();
            inValue.Body = new WorldlineLiveServiceReference.GetBankListRequestBody();
            return ((WorldlineLiveServiceReference.SoapDemoSoap)(this)).GetBankListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldlineLiveServiceReference.GetBranchDetailsByIfscResponse> WorldlineLiveServiceReference.SoapDemoSoap.GetBranchDetailsByIfscAsync(WorldlineLiveServiceReference.GetBranchDetailsByIfscRequest request)
        {
            return base.Channel.GetBranchDetailsByIfscAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldlineLiveServiceReference.GetBranchDetailsByIfscResponse> GetBranchDetailsByIfscAsync(string IfscCode)
        {
            WorldlineLiveServiceReference.GetBranchDetailsByIfscRequest inValue = new WorldlineLiveServiceReference.GetBranchDetailsByIfscRequest();
            inValue.Body = new WorldlineLiveServiceReference.GetBranchDetailsByIfscRequestBody();
            inValue.Body.IfscCode = IfscCode;
            return ((WorldlineLiveServiceReference.SoapDemoSoap)(this)).GetBranchDetailsByIfscAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorldlineLiveServiceReference.GetBranchDetailsByBankResponse> WorldlineLiveServiceReference.SoapDemoSoap.GetBranchDetailsByBankAsync(WorldlineLiveServiceReference.GetBranchDetailsByBankRequest request)
        {
            return base.Channel.GetBranchDetailsByBankAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorldlineLiveServiceReference.GetBranchDetailsByBankResponse> GetBranchDetailsByBankAsync(string bankName, int offset, int rowCount)
        {
            WorldlineLiveServiceReference.GetBranchDetailsByBankRequest inValue = new WorldlineLiveServiceReference.GetBranchDetailsByBankRequest();
            inValue.Body = new WorldlineLiveServiceReference.GetBranchDetailsByBankRequestBody();
            inValue.Body.bankName = bankName;
            inValue.Body.offset = offset;
            inValue.Body.rowCount = rowCount;
            return ((WorldlineLiveServiceReference.SoapDemoSoap)(this)).GetBranchDetailsByBankAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SoapDemoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SoapDemoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SoapDemoSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://bankdetailsdemo.azurewebsites.net/WebServices/SoapDemo.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SoapDemoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://bankdetailsdemo.azurewebsites.net/WebServices/SoapDemo.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SoapDemoSoap,
            
            SoapDemoSoap12,
        }
    }
}
